spring:
  kafka:
    bootstrap-servers: 54.180.124.89:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer