server:
  port: 0

spring:
  kafka:
    bootstrap-servers:
      - 43.201.96.57:9092
      - 43.201.96.57:19092
      - 43.201.96.57:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
